#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

# Load environment variables from .env if present
if [ -f ".env" ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Validate Docker credentials
echo -e "${YELLOW}Validating Docker access token...${NC}"
echo "${DOCKER_ACCESS_TOKEN}" | docker login -u ${DOCKER_USERNAME} --password-stdin
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker login failed. Please check your DOCKER_ACCESS_TOKEN. Exiting...${NC}"
    exit 1
fi

echo -e "${GREEN}Docker login successful! Proceeding with the deployment...${NC}"

# Build Docker image
echo -e "${YELLOW}Building Docker image...${NC}"
docker build -t ${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:latest -f Dockerfile .
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker image build failed. Exiting...${NC}"
    exit 1
fi

# Push Docker image to Docker Hub
echo -e "${YELLOW}Pushing Docker image to Docker Hub...${NC}"
docker push ${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:latest
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker image push failed. Exiting...${NC}"
    exit 1
fi

echo -e "${GREEN}Docker image successfully pushed to Docker Hub!${NC}"
