#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

# Load environment variables from .env if present
if [ -f ".env" ]; then
    export $(grep -v '^#' .env | xargs)
fi

if [ -z "$DOCKER_USERNAME" ]; then
    handle_error "Error: DOCKER_USERNAME is not set. Please ensure it's defined in your .env file or as an environment variable."
fi

if [ -z "$DOCKER_ACCESS_TOKEN" ]; then
    handle_error "Error: DOCKER_ACCESS_TOKEN is not set. Please ensure it's defined in your .env file or as an environment variable."
fi

if [ -z "$DOCKER_REPO_NAME" ]; then
    handle_error "Error: DOCKER_REPO_NAME is not set. Please ensure it's defined in your .env file or as an environment variable."
fi

# Validate Docker credentials
echo -e "${YELLOW}Validating Docker access token...${NC}"
echo "${DOCKER_ACCESS_TOKEN}" | docker login -u ${DOCKER_USERNAME} --password-stdin
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker login failed. Please check your DOCKER_ACCESS_TOKEN. Exiting...${NC}"
    exit 1
fi

echo -e "${GREEN}Docker login successful!${NC}"
echo -e " "

# Build Docker image
echo -e "${YELLOW}Building and tagging Docker image...${NC}"
docker build -t ${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:latest .
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker image build and tagging failed. Exiting...${NC}"
    echo -e " "
    exit 1
fi

echo -e " "
echo -e "${GREEN}Docker image built and tagged successfully!${NC}"
echo -e " "