#!/bin/bash

# Set Colors and handle errors
source sdlc/colors

echo -e "${YELLOW}Starting testing...${NC}"

# Run pylint
echo -e "${YELLOW}Running pylint...${NC}"
pylint **/*.py
if [ $? -ne 0 ]; then
    echo -e "${RED}Pylint failed. Exiting...${NC}"
    exit 1
else
    echo -e "${GREEN}Pylint passed!${NC}"
fi

# Run mypy
echo -e "${YELLOW}Running mypy...${NC}"
mypy **/*.py
if [ $? -ne 0 ]; then
    echo -e "${RED}Mypy failed. Exiting...${NC}"
    exit 1
else
    echo -e "${GREEN}Mypy passed!${NC}"
fi

# Run tests
echo -e "${YELLOW}Running tests...${NC}"
pytest
if [ $? -ne 0 ]; then
    echo -e "${RED}Tests failed. Exiting...${NC}"
    exit 1
else
    echo -e "${GREEN}Tests passed!${NC}"
fi

echo -e "${GREEN}Test script completed successfully!${NC}"
