#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

echo -e "${YELLOW}Starting testing...${NC}"

# Run pylint
echo -e "${YELLOW}Running pylint...${NC}"
pylint **/*.py
if [ $? -ne 0 ]; then
    echo -e "${RED}Pylint failed. Exiting...${NC}"
    exit 1
else
    echo -e "${GREEN}Pylint passed!${NC}"
fi

# Run mypy
echo -e "${YELLOW}Running mypy...${NC}"
mypy **/*.py
if [ $? -ne 0 ]; then
    echo -e "${RED}Mypy failed. Exiting...${NC}"
    exit 1
else
    echo -e "${GREEN}Mypy passed!${NC}"
fi

# Run Ruff
echo -e "${YELLOW}Running Ruff...${NC}"
ruff check **/*.py
if [ $? -ne 0 ]; then
    echo -e "${RED}Ruff failed. Exiting...${NC}"
    exit 1
else
    echo -e "${GREEN}Ruff passed!${NC}"
fi

echo -e "${GREEN}Linter checks completed successfully!${NC}"
