#!/bin/bash

# Set Colors and handle errors
sdlc/colors

# Collect static files, compile assets, etc...
echo -e "${YELLOW}Building the project...${NC}"
python app/manage.py collectstatic --noinput
if [ $? -ne 0 ]; then
    handle_error "${RED}Build failed while collecting static files. Exiting...${NC}"
fi