#!/bin/bash

# Set Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
ORANGE='\033[0;38;5;214m'
BLUE='\033[38;2;0;255;255m'
NC='\033[0m'

# Function to handle errors
handle_error() {
    echo -e "${RED}$1${NC}"
    exit 1
}