#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

# Load & Set Environmental Variables
sdlc/set_envars

echo -e " "
echo -e "${YELLOW}Building project...${NC}"
echo -e " "

# Install dependencies
sdlc/install_dependencies
if [ $? -ne 0 ]; then
    handle_error "Install Dependencies script failed. Exiting deployment..."
fi

# Reset pip requirements.txt file
sdlc/reset_requirements

# Collect static files, compile assets, etc...
sdlc/collect_static
if [ $? -ne 0 ]; then
    handle_error "Collect Static files failed. Exiting deployment..."
fi

# Make migrations
sdlc/migrate
if [ $? -ne 0 ]; then
    handle_error "Migration script failed. Exiting deployment..."
fi

# Build Docker image
sdlc/build
if [ $? -ne 0 ]; then
    handle_error "Build script failed. Exiting deployment..."
fi

# Push Docker image to Docker Hub
echo -e "${YELLOW}Pushing Docker image to Docker Hub...${NC}"
docker push ${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:latest
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker image push failed. Exiting...${NC}"
    echo -e " "
    exit 1
fi

echo -e "${GREEN}Docker image successfully pushed to Docker Hub!${NC}"
echo -e "${GREEN}Deployment script completed successfully!${NC}"
echo -e " "
