#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${YELLOW}Checking if requirements are satisfied...${NC}"
pip freeze > installed_packages.txt
if ! diff -q <(sort requirements.txt) <(sort installed_packages.txt) > /dev/null 2>&1; then
    echo -e "${YELLOW}Requirements not satisfied. Installing dependencies...${NC}"
    pip install -r requirements.txt
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to install dependencies. Exiting...${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}All requirements are already satisfied. Skipping pip install.${NC}"
fi
rm installed_packages.txt
