#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

echo -e "${YELLOW}Checking if dependencies are satisfied...${NC}"
pip freeze > installed_packages.txt
if ! diff -q <(sort requirements.txt) <(sort installed_packages.txt) > /dev/null 2>&1; then
    echo -e "${YELLOW}Requirements not satisfied. Installing dependencies...${NC}"
    pip install -r requirements.txt
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to install dependencies. Exiting...${NC}"
        echo -e " "
        exit 1
    else
        echo -e "${GREEN}Successfully installed dependencies!${NC}"
        echo -e " "
    fi
else
    echo -e "${GREEN}All requirements are already satisfied. Skipping pip install...${NC}"
    echo -e " "
fi
rm installed_packages.txt
