#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

echo -e "${YELLOW}Reseting requirements.txt...${NC}"
rm requirements.txt

echo -e "${YELLOW}Updating requirements.txt...${NC}"
pip3 freeze > requirements.txt

cat requirements.txt

echo -e "${GREEN}Successfully updated requirements.txt!${NC}"
echo -e " "