#!/bin/bash

# Set Colors and handle errors
sdlc/colors

echo -e "${YELLOW}Reseting requirements.txt...${NC}"
rm requirements.txt

echo -e "${YELLOW}Updating requirements.txt...${NC}"
pip3 freeze > requirements.txt

echo -e " "
cat requirements.txt