services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPWD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 vonfitbjjInsights.wsgi:application --chdir app
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  postgres_data: