# Generated by Django 5.0.6 on 2024-06-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metainsights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebooktoken',
            name='user',
        ),
    ]
