# Generated by Django 5.0.6 on 2024-06-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metainsights', '0002_remove_facebooktoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookToken',
        ),
    ]
