# Generated by Django 5.0.6 on 2024-06-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metainsights', '0003_delete_facebooktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
    ]
