# Generated by Django 5.0.6 on 2024-06-01 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metainsights', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooktoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebooktoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
