# Generated by Django 5.0.6 on 2024-06-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metainsights', '0007_facebookpage_cli_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='ig_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
