# Generated by Django 5.0.6 on 2024-06-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('income_level', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('interests_hobbies', models.TextField()),
                ('lifestyle', models.TextField()),
                ('values_beliefs', models.TextField()),
                ('personality_traits', models.TextField()),
                ('attitudes', models.TextField()),
                ('buying_behavior', models.TextField()),
                ('brand_loyalty', models.TextField()),
                ('shopping_preferences', models.TextField(choices=[('online', 'Online'), ('offline', 'Offline')])),
                ('purchase_influencers', models.TextField()),
                ('primary_goals', models.TextField()),
                ('challenges', models.TextField()),
                ('product_help', models.TextField()),
                ('social_media_platforms', models.TextField()),
                ('favorite_websites_blogs', models.TextField()),
                ('influencers_followed', models.TextField()),
                ('content_types', models.TextField()),
                ('awareness_stage', models.TextField()),
                ('consideration_stage', models.TextField()),
                ('decision_stage', models.TextField()),
            ],
        ),
    ]
