# Generated by Django 5.0.6 on 2024-06-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_avatar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='gender',
            field=models.TextField(choices=[('female', 'Female'), ('male', 'Male')]),
        ),
    ]
