# Generated by Django 5.0.6 on 2024-06-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_alter_avatar_age_alter_avatar_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='attitudes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='awareness_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='brand_loyalty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='buying_behavior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='consideration_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='content_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='decision_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='favorite_websites_blogs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='gender',
            field=models.TextField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='income_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='influencers_followed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='interests_hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='lifestyle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='personality_traits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='primary_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='product_help',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='purchase_influencers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='shopping_preferences',
            field=models.TextField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='social_media_platforms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='values_beliefs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
