name: Django CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_check:
    name: Security Checks
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run security checks with Bandit
      run: |
        pip install --upgrade pip
        pip install bandit
        bandit -r app/vonfitbjjInsights/ -ll
  
  linters:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pylint mypy pytest

    - name: Run Code Quality Checks
      run: |
        bash sdlc/check_code

  deployment_check:
    name: Deployment Verification
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        bash sdlc/install_dependencies

    - name: Run Django checks
      env:
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ vars.DEBUG }}
        DBNAME: ${{ secrets.DBNAME }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPWD: ${{ secrets.PGPWD }}
        PGHOST: ${{ secrets.PGHOST }}
        PGPORT: ${{ secrets.PGPORT }}
        FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
        FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
        FACEBOOK_USER_ID: ${{ secrets.FACEBOOK_USER_ID }}
      run: |
        python app/manage.py check
        python app/manage.py test

    - name: Deploy Docker Image
      env:
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        DOCKER_REPO_NAME: ${{ vars.DOCKER_REPO_NAME }}
        DJANGO_PROJECT_NAME: ${{ vars.DJANGO_PROJECT_NAME }}
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ vars.DEBUG }}
        DBNAME: ${{ secrets.DBNAME }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPWD: ${{ secrets.PGPWD }}
        PGHOST: ${{ secrets.PGHOST }}
        PGPORT: ${{ secrets.PGPORT }}
        FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
        FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
        FACEBOOK_USER_ID: ${{ secrets.FACEBOOK_USER_ID }}
      run: |
        bash sdlc/deploy
