name: Django CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: '/github/workflow/analysis'

  security_check:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run security checks with Bandit
      run: |
        pip install --upgrade pip
        pip install bandit
        bandit -r app/vonfitbjjInsights/ -ll

  deployment_check:
    name: Deployment Verification
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        bash sdlc/install_dependencies

    - name: Run Django checks
      run: |
        python app/manage.py check
        python app/manage.py test

    - name: Build and Push Docker Image
      env:
        DJANGO_PROJECT_NAME: ${{ secrets.DJANGO_PROJECT_NAME }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
      run: |
        bash sdlc/deploy
